{{- if and (eq .Values.ingress.className "traefik") (.Values.ingress.sablier.enabled) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: {{ include "otrs.fullname" . }}
spec:
    plugin:
        sablier:
            dynamic:
                displayName: your OTRS instance...
                refreshFrequency: {{ .Values.ingress.sablier.refreshFrequency }}
                showDetails: {{ .Values.ingress.sablier.showDetails | toString | quote }}
                theme: hacker-terminal
            names: deployment_{{ .Release.Namespace }}_{{ include "otrs.fullname" . }}_{{ .Values.replicaCount }}
            sablierUrl: {{ .Values.ingress.sablier.url | quote }}
            sessionDuration: {{ .Values.ingress.sablier.sessionDuration }}
{{- end }}