{{- if and (.Values.persistence.enabled) (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "otrs.fullname" . }}"
  labels:
    {{- include "otrs.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if and (.Values.persistence.storageClass) (ne "-" .Values.persistence.storageClass) }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}