apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "otrs.fullname" . }}"
type: Opaque
data:
    {{- if .Values.mariadb.enabled }}
    OTRS_DB_NAME: {{ .Values.mariadb.auth.database | b64enc }}
    OTRS_DB_HOST: {{ printf "%s-mariadb" .Release.Name | b64enc }}
    OTRS_DB_PORT: {{ printf "%d" "3306" | b64enc}}
    OTRS_DB_USER: {{ .Values.mariadb.auth.username | b64enc }}
    OTRS_DB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc }}
    MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | b64enc }}
    {{- else }}
    OTRS_DB_NAME: {{ .Values.properties.db.name | b64enc }}
    OTRS_DB_HOST: {{ .Values.properties.db.host | b64enc }}
    OTRS_DB_PORT: {{ printf "%d" .Values.properties.db.port | b64enc}}
    OTRS_DB_USER: {{ .Values.properties.db.otrsUsername | b64enc }}
    OTRS_DB_PASSWORD: {{ .Values.properties.db.otrsPassword | b64enc }}
    MYSQL_ROOT_PASSWORD: {{ .Values.properties.db.rootPassword | b64enc }}
    {{- end }}
    OTRS_INSTALL: {{ .Values.properties.otrsInstall | b64enc }}
    OTRS_BACKUP_TIME: {{ .Values.properties.otrsBackupTime | b64enc }}
    {{- if .Values.properties.otrsRootPassword }}
    OTRS_ROOT_PASSWORD: {{ .Values.properties.otrsRootPassword | b64enc }}
    {{- end }}